/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-03-10 06:24:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mem_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1646879685963L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1646614090411L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640241526733L));
    _jspx_dependants.put("jar:file:/C:/Java/myjsp2022/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Project_header</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/proj_css.css\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("				<h2>\r\n");
      out.write("					<a href=\"/\">모아맛집</a>\r\n");
      out.write("				</h2>\r\n");
      out.write("				<nav>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("				<div id=\"header_back\"></div>\r\n");
      out.write("		</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section id=\"contentwrap\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"content_bottom\" class=\"top_padding\">\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"/\">\r\n");
      out.write("                        <img src=\"../resources/img/logo.png\" alt=\"메인로고\" style=\"height:220px\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             <div class=\"t-margin-70\">\r\n");
      out.write("             <h2 style=\"margin-bottom: 20px \">회원가입</h2>\r\n");
      out.write("             \r\n");
      out.write("            <form action=\"joinForm\" id=\"joinForm\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <table id=\"regist_table\" width=\"50%\" style= \"font-size: 15px; text-align: center;\">\r\n");
      out.write("                   <tr>\r\n");
      out.write("                       <td style=\"width:20%;  height:50px\" >아이디</td>\r\n");
      out.write("                       <td colspan=\"4\"><input type=\"text\" name=\"id\" id=\"id\" style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("						<td style=\"width: 20%\">\r\n");
      out.write("							<input type=\"button\" class=\"btn_check\" value=\"중복체크\" onclick=\"IdCheck()\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                       <td style=\"height:50px\" >비밀번호</td>\r\n");
      out.write("                       <td  colspan=\"4\"><input type=\"password\" name=\"pw\" id=\"pw\" style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                     <tr>\r\n");
      out.write("                       <td style=\"height:50px\" >비밀번호 확인</td>\r\n");
      out.write("                       <td  colspan=\"4\"><input type=\"password\" name=\"pwCheck\"  id=\"pwCheck\"style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                     <tr>\r\n");
      out.write("                       <td style=\"height:50px\" >이름</td>\r\n");
      out.write("                       <td  colspan=\"4\"><input type=\"text\" name=\"name\"  id=\"name\"style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                   		<td style=\"height:50px\" >전화번호</td>\r\n");
      out.write("                   		<td>\r\n");
      out.write("                   			<select name=\"phone\" style=\"height: 40px; width: 90%; text-align: center; border: none;\">\r\n");
      out.write("                   				<option value=\"010\">010</option>\r\n");
      out.write("                   				<option value=\"011\">011</option>\r\n");
      out.write("                   				<option value=\"017\">017</option> \r\n");
      out.write("                   			</select>\r\n");
      out.write("                   		</td>\r\n");
      out.write("                        <td colspan=\"2\" width=\"20%\"><input type=\"text\" name=\"phone1\"  id=\"phone1\" style=\"border: none; background-color: #ffffff; height: 40px; width: 90%; text-align: center;\"></td>\r\n");
      out.write("                        <td width=\"20%\"><input type=\"text\" name=\"phone2\"  id=\"phone2\" style=\"border: none; background-color: #ffffff; height: 40px; width: 90%; text-align: center;\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                       <td style=\"height:50px\" >닉네임</td>\r\n");
      out.write("                       <td  colspan=\"4\"><input type=\"text\" name=\"nickname\"  id=\"nickname\"style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("                       <td>\r\n");
      out.write("							<input type=\"button\" class=\"btn_check\" value=\"중복체크\" onclick=\"NickCheck()\">\r\n");
      out.write("						</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td style= \"height:50px\">성별</td>\r\n");
      out.write("                        <td colspan=\"2\" style=\"text-align: center\">\r\n");
      out.write("                        <input type=\"radio\" id=\"male\" name=\"gender\" value=\"남\" checked>\r\n");
      out.write("                            <label for=\"male\">남성</label>\r\n");
      out.write("                            \r\n");
      out.write("                        <td colspan=\"2\" style=\"text-align: center\">\r\n");
      out.write("                       <input type=\"radio\" id=\"female\" name=\"gender\" value=\"여\">\r\n");
      out.write("                            <label for=\"female\">여성</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                       <td style=\"height:50px\"> 주소</td>\r\n");
      out.write("                       <td  colspan=\"4\"><input type=\"text\" name=\"address\" id=\"address\" style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\">\r\n");
      out.write("                    </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                       <td style=\"height:50px\"> 이메일</td>\r\n");
      out.write("                       <td  colspan=\"1\"><input type=\"email\" name=\"email\" id=\"email\"style=\"border: none; background-color: #ffffff; height: 40px; width: 90%; text-align: center;\">\r\n");
      out.write("                       <td colspan=\"3\" style=\"width: 70%; \">\r\n");
      out.write("                    		<select name=\"emailAd\" id=\"emailAd\" style=\"width: 80%; height: 40px;\">\r\n");
      out.write("                    			<option value=\"\">이메일 선택</option>\r\n");
      out.write("                   				<option value=\"@naver.com\">@naver.com</option>\r\n");
      out.write("                   				<option value=\"@nate.com\">@nate.com</option>\r\n");
      out.write("                   				<option value=\"@gmail.com\">@gamil.com</option>\r\n");
      out.write("                   				<option value=\"@daum.net\">@daum.net</option>\r\n");
      out.write("                   			</select>\r\n");
      out.write("                    	</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    	<td style=\"height:50px\"> 본인 확인 질문</td>\r\n");
      out.write("                    	<td colspan=\"4\">\r\n");
      out.write("                    		<select name=\"question\" id=\"question\" style=\"height: 40px; width: 100%; text-align: center; border: none;\">\r\n");
      out.write("                    			<option value=\"\">새로운 질문 선택</option>\r\n");
      out.write("                   				<option value=\"1\">처음으로 샀던 자동차는 ?</option>\r\n");
      out.write("                   				<option value=\"2\">고등학교 시절 살았던 동네는?</option>\r\n");
      out.write("                   				<option value=\"3\">첫 해외여행 장소는?</option>\r\n");
      out.write("                   				<option value=\"4\">처음으로 플레이한 게임은?</option>\r\n");
      out.write("                   				<option value=\"5\">가장 좋아하는 스포츠 팀이나 선수 이름은?</option>  \r\n");
      out.write("                   			</select>\r\n");
      out.write("                    	</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    		<td style=\" height:50px\"> 본인 확인 답변</td>\r\n");
      out.write("                    		<td colspan=\"4\"><input type=\"text\" name=\"answer\" id=\"answer\" placeholder=\"본인 확인 답변 입력\"style=\"border: none; background-color: #ffffff; height: 40px; width: 100%; text-align: center;\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("                <br>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"btn_area double\">\r\n");
      out.write("                	<div id=\"btnCancel\" onclick=\"history.go(-1)\">\r\n");
      out.write("                		<a href=\"#\" role=\"button\">취소</a>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<div>\r\n");
      out.write("                		<input id=\"btnSubmit\" type=\"button\" value=\"확인\" onclick=\"joinCheck()\">\r\n");
      out.write("                	</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("<script\r\n");
      out.write("									src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("								<script type=\"text/javascript\">\r\n");
      out.write("									function IdCheck() {\r\n");
      out.write("										var id = $('#id').val(); //id태그 value에 접근\r\n");
      out.write("										var user_id = {\r\n");
      out.write("											\"id\" : id\r\n");
      out.write("										}; //전송할 데이터의 key값\r\n");
      out.write("\r\n");
      out.write("										if (id.length < 4) {\r\n");
      out.write("											alert(\"아이디는 4글자 이상이여야 합니다.\");\r\n");
      out.write("										} else {\r\n");
      out.write("											//먼저 ajax를 지원하는 json을 사용하기 위해 라이브러리 필요\r\n");
      out.write("											//json은 {키 : 값}을 구조를 가지고 있는 데이터 묶음\r\n");
      out.write("											//ajax문법\r\n");
      out.write("											$\r\n");
      out.write("													.ajax({\r\n");
      out.write("														type : \"post\", //요청 형식\r\n");
      out.write("														url : \"checkId\", //요청 주소\r\n");
      out.write("														data : user_id, //서버에 전송할 데이터 json형식\r\n");
      out.write("														//dataType : \"json\",//서버에 요청 후 리턴해 주는 타입\r\n");
      out.write("														error : function(\r\n");
      out.write("																request, error) {\r\n");
      out.write("															alert(error\r\n");
      out.write("																	+ \"\\n\"\r\n");
      out.write("																	+ request.status);\r\n");
      out.write("														},\r\n");
      out.write("														success : function(\r\n");
      out.write("																result) {\r\n");
      out.write("															//ajax통신에 성공했을 때 호출될 자바 스크립트 함수,\r\n");
      out.write("															//결과 여부가 result매개 변수로 전달됨.\r\n");
      out.write("															console\r\n");
      out.write("																	.log(\"성공 실패 여부 : \"\r\n");
      out.write("																			+ result);\r\n");
      out.write("\r\n");
      out.write("															if (result == 1) { //중복되는 아이디가 존재함.\r\n");
      out.write("																alert(\"이미 존재하는 아이디 입니다.\");\r\n");
      out.write("															} else {\r\n");
      out.write("																alert(\"사용가능한 아이디 입니다.\");\r\n");
      out.write("																$(\"#id\")\r\n");
      out.write("																		.attr(\r\n");
      out.write("																				\"readonly\",\r\n");
      out.write("																				true);\r\n");
      out.write("															}\r\n");
      out.write("														}\r\n");
      out.write("													}) //$.ajax 동작 부분\r\n");
      out.write("										} //else 종료 부분\r\n");
      out.write("									}\r\n");
      out.write("									//닉네임 중복 체크\r\n");
      out.write("									function NickCheck() {\r\n");
      out.write("										var nickname = $('#nickname').val(); //nickname태그 value에 접근\r\n");
      out.write("										var user_Nick = {\r\n");
      out.write("											\"nickname\" : nickname\r\n");
      out.write("										}; //전송할 데이터의 key값\r\n");
      out.write("\r\n");
      out.write("										if (nickname.length < 2) {\r\n");
      out.write("											alert(\"닉네임는 2글자 이상이여야 합니다.\");\r\n");
      out.write("										} else {\r\n");
      out.write("											//먼저 ajax를 지원하는 json을 사용하기 위해 라이브러리 필요\r\n");
      out.write("											//json은 {키 : 값}을 구조를 가지고 있는 데이터 묶음\r\n");
      out.write("											//ajax문법\r\n");
      out.write("											$\r\n");
      out.write("													.ajax({\r\n");
      out.write("														type : \"post\", //요청 형식\r\n");
      out.write("														url : \"checkNname\", //요청 주소\r\n");
      out.write("														data : user_Nick, //서버에 전송할 데이터 json형식\r\n");
      out.write("														//dataType : \"json\",//서버에 요청 후 리턴해 주는 타입\r\n");
      out.write("														error : function(\r\n");
      out.write("																request, error) {\r\n");
      out.write("															alert(error\r\n");
      out.write("																	+ \"\\n\"\r\n");
      out.write("																	+ request.status);\r\n");
      out.write("														},\r\n");
      out.write("														success : function(\r\n");
      out.write("																result) {\r\n");
      out.write("															//ajax통신에 성공했을 때 호출될 자바 스크립트 함수,\r\n");
      out.write("															//결과 여부가 result매개 변수로 전달됨.\r\n");
      out.write("															console\r\n");
      out.write("																	.log(\"성공 실패 여부 : \"\r\n");
      out.write("																			+ result);\r\n");
      out.write("\r\n");
      out.write("															if (result == 1) { //중복되는 닉네임이 존재함.\r\n");
      out.write("																alert(\"이미 존재하는 닉네임 입니다.\");\r\n");
      out.write("															} else {\r\n");
      out.write("																alert(\"사용가능한 닉네임 입니다.\");\r\n");
      out.write("																$(\"#nickname\")\r\n");
      out.write("																		.attr(\r\n");
      out.write("																				\"readonly\",\r\n");
      out.write("																				true);\r\n");
      out.write("															}\r\n");
      out.write("														}\r\n");
      out.write("													}) //$.ajax 동작 부분\r\n");
      out.write("										} //else 종료 부분\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									//회원가입 체크\r\n");
      out.write("									function joinCheck() {\r\n");
      out.write("										//attr(속성, 변경할 값) 함수는 해당 ID태그의 내부 속성을 변경\r\n");
      out.write("										//attr(속성) 함수의 매개값이 하나라면 해당 속성여부를 확인\r\n");
      out.write("										//val() 함수는 해당 ID태그의 값을 확인\r\n");
      out.write("										//focus() 함수는 해당 ID태그의 마우스 커서를 위치시킨다.\r\n");
      out.write("										//submit() 함수는 해당 ID태그의 form 을 서밋처리\r\n");
      out.write("										if ($(\"#id\").val().length < 1) {\r\n");
      out.write("											alert(\"아이디를 입력하세요.\");\r\n");
      out.write("										} else if (!$(\"#id\").attr(\"readonly\")) {\r\n");
      out.write("											alert(\"아이디 중복 체크를 해야합니다.\");\r\n");
      out.write("										} else if ($(\"#name\").val().length < 1) {\r\n");
      out.write("											alert(\"이름을 입력하세요.\");\r\n");
      out.write("										} else if ($(\"#pw\").val().length < 1) {\r\n");
      out.write("											alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("										} else if ($(\"#pw\").val() != $(\r\n");
      out.write("												\"#pwCheck\").val()) {\r\n");
      out.write("											alert(\"비밀번호 확인란을 확인해주세요.\");\r\n");
      out.write("											$(\"#pwCheck\").focus();\r\n");
      out.write("										} else if ($(\"#name\").val().length < 1) {\r\n");
      out.write("											alert(\"이름을 입력하세요.\");\r\n");
      out.write("										} else if ($(\"#phone1\").val() == \"\"\r\n");
      out.write("												|| $(\"#phone1\").val().length != 4) {\r\n");
      out.write("											alert(\"폰 번호(앞자리)는 4자리수로만 입력하세요.\");\r\n");
      out.write("										} else if (isNaN($(\"#phone1\").val())) {\r\n");
      out.write("											alert(\"휴대폰 번호를 숫자로만 입력해 주세요.\")\r\n");
      out.write("										} else if ($(\"#phone2\").val() == \"\"\r\n");
      out.write("												|| $(\"#phone2\").val().length != 4) {\r\n");
      out.write("											alert(\"폰 번호(뒷자리)는 4자리수로만 입력하세요.\");\r\n");
      out.write("										} else if (isNaN($(\"#phone1\").val())) {\r\n");
      out.write("											alert(\"휴대폰 번호를 숫자로만 입력해 주세요.\")\r\n");
      out.write("										} else if ($(\"#nickname\").val().length < 1) {\r\n");
      out.write("											alert(\"닉네임을 입력하세요.\");\r\n");
      out.write("										} else if ($(\"#address\").val().length < 1) {\r\n");
      out.write("											alert(\"주소를 입력하세요.\");\r\n");
      out.write("										} else if ($(\"#question\").val() == '') {\r\n");
      out.write("											alert(\"본인 확인 질문을 선택 해주세요.\");\r\n");
      out.write("											return false;\r\n");
      out.write("										} else if ($(\"#answer\").val().length < 1) {\r\n");
      out.write("											alert(\"본인 확인 답변을 입력해주세요.\");\r\n");
      out.write("										} else if (confirm(\"회원 가입 하시겠습니까?\")) {\r\n");
      out.write("											$(\"#joinForm\").submit();\r\n");
      out.write("										}\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("								</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <footer id=\"footer\">\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("               <div class=\"footer_menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">사이트 도움말</a></li>\r\n");
      out.write("                    <li><a href=\"#\">사이트 이용약관</a></li>\r\n");
      out.write("\r\n");
      out.write("                    <li><a href=\"#\"><strong>개인정보취급방침</strong></a></li>\r\n");
      out.write("\r\n");
      out.write("                    <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <br>\r\n");
      out.write("                <address>\r\n");
      out.write("                    Copyright ©\r\n");
      out.write("                    <strong>team 학원에좀나와줘</strong>\r\n");
      out.write("                    All Rights Reserved.\r\n");
      out.write("                    \r\n");
      out.write("                </address>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../include/header.jsp(33,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"bor-r bor-l\"><a href=\"/member/mem_mypage\">내정보</a>\r\n");
          out.write("									<ul class=\"bor-r\" id=\"submenu\">\r\n");
          out.write("										<li><a href=\"/member/mem_modifyCheck\">회원 정보 수정</a></li>\r\n");
          out.write("										<li><a href=\"##\">회원 정보 탈퇴</a></li>\r\n");
          out.write("										<li class=\"bor-b\"><a href=\"/member/mem_alterPw\">비밀번호 변경</a></li>\r\n");
          out.write("									</ul></li>\r\n");
          out.write("								<li><a href=\"/member/mem_logout\">로그아웃</a></li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"bor-r bor-l\"><a href=\"/member/login\">로그인</a></li>\r\n");
          out.write("								<li><a href=\"/member/join\">회원가입</a></li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
